---
- vsphere_guest:
    vcenter_hostname: esx.lab
    username: root
    password: "{{ esx_password }}"
    guest: newvm001
    state: powered_on
    vm_extra_config:
      vcpu.hotadd: yes
      mem.hotadd:  yes
      notes: This is a test VM
#      folder: 
    vm_disk:
      disk1:
        size_gb: 10
        type: thin
        datastore: datastore1
        # VMs can be put into folders. The value given here is either the full path
        # to the folder (e.g. production/customerA/lamp) or just the last component
        # of the path (e.g. lamp):
        folder: newvm001
    vm_nic:
      nic1:
        type: vmxnet3
        network: VM Network
        network_type: standard
#       nic2:
#        type: vmxnet3
#        network: dvSwitch Network
#        network_type: dvs
    vm_hardware:
      memory_mb: 2048
      num_cpus: 1
#      osid: rhel7-64
      osid: centos64Guest
      scsi: paravirtual
      vm_cdrom:
        type: "iso"
        iso_path: "/vmfs/volumes/datastore1/foreman-discovery-image-3.1.1-16.iso"
#      vm_floppy:
#        type: "image"
#        image_path: "DatastoreName/floppy-image.flp"
    esxi:
      datacenter: ha-datacenter
      hostname: esx.lab

